language: scala

scala:
  - 2.10.6
  - 2.11.11
  - 2.12.3

env:
  - JDK=oraclejdk7
  - JDK=oraclejdk8

before_script:
  - jdk_switcher use $JDK

matrix:
  exclude:
    - scala: 2.12.3
      env: JDK=oraclejdk7
