language: scala

scala:
  - 2.11.12
  - 2.12.6

env:
  - JDK=oraclejdk7
  - JDK=oraclejdk8
  - JDK=oraclejdk9

before_script:
  - jdk_switcher use $JDK

matrix:
  exclude:
    - scala: 2.12.6
      env: JDK=oraclejdk7
