addSbtPlugin("org.scalameta"    % "sbt-scalafmt"              % "2.6.0")
addSbtPlugin("org.typelevel"    % "sbt-tpolecat"              % "0.5.3")
addSbtPlugin("org.wartremover"  % "sbt-wartremover"           % "3.5.6")
addSbtPlugin("org.scoverage"    % "sbt-scoverage"             % "2.3.1")
addSbtPlugin("ch.epfl.scala"    % "sbt-scalafix"              % "0.14.6")
addSbtPlugin("com.github.cb372" % "sbt-explicit-dependencies" % "0.3.1")
