addSbtPlugin("org.scalameta"    % "sbt-scalafmt"              % "2.5.2")
addSbtPlugin("org.typelevel"    % "sbt-tpolecat"              % "0.5.1")
addSbtPlugin("org.wartremover"  % "sbt-wartremover"           % "3.2.0")
addSbtPlugin("org.scoverage"    % "sbt-scoverage"             % "2.1.0")
addSbtPlugin("ch.epfl.scala"    % "sbt-scalafix"              % "0.12.1")
addSbtPlugin("com.github.cb372" % "sbt-explicit-dependencies" % "0.3.1")
