name: Continuous integration

on:
  push:
    branches: ['**']

jobs:
  lint-and-test:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '23'
          cache: sbt

      - uses: sbt/setup-sbt@v1

      - name: Check linting and formatting
        run: sbt 'scalafixAll --check' scalafmtSbtCheck scalafmtCheck

      - name: Unit test
        run: sbt +test
