name: Continuous integration

on:
  push:
    branches: ['**']

jobs:
  lint-and-test:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
          cache: sbt

      - run: sbt 'scalafixAll --check' scalafmtSbtCheck scalafmtCheck

      - run: sbt +test
